draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: true
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
  svg_extra_style: |
    .trans,
    .none,
    .ghost {
      opacity: 0.4;
    }
parse_config:
  sticky_label: OSM
  toggle_label: TG
  tap_toggle_label: TTG
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  raw_binding_map:
    # Modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:toggle-switch$$

    # Empty
    "&none":
      type: trans

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    # Bluetooth
    "&bt BT_SEL 0":
      tap: $$mdi:bluetooth-connect$$
      hold: 1
    "&bt BT_SEL 1":
      tap: $$mdi:bluetooth-connect$$
      hold: 2
    "&bt BT_SEL 2":
      tap: $$mdi:bluetooth-connect$$
      hold: 3
    "&bt BT_SEL 3":
      tap: $$mdi:bluetooth-connect$$
      hold: 4
    "&bt BT_SEL 4":
      tap: $$mdi:bluetooth-connect$$
      hold: 5
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$

    # Reset
    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$
    "&rst_boot 0 0":
      type: bootloader
      tap: $$mdi:backup-restore$$
      hold: $$mdi:progress-download$$

    # Mouse
    "&mmv MOVE_LEFT":
      tap: $$mdi:mouse$$
      hold: $$mdi:arrow-left-bold-outline$$
    "&mmv MOVE_DOWN":
      tap: $$mdi:mouse$$
      hold: $$mdi:arrow-down-bold-outline$$
    "&mmv MOVE_UP":
      tap: $$mdi:mouse$$
      hold: $$mdi:arrow-up-bold-outline$$
    "&mmv MOVE_RIGHT":
      tap: $$mdi:mouse$$
      hold: $$mdi:arrow-right-bold-outline$$
    "&mkp LCLK": $$mdi:mouse-left-click$$
    "&mkp RCLK": $$mdi:mouse-right-click$$
    "&mkp MCLK": $$mdi:mouse-scroll-wheel$$
    "&msc SCRL_LEFT":
      tap: $$mdi:mouse-scroll-wheel$$
      hold: $$mdi:arrow-left-bold-circle-outline$$
    "&msc SCRL_DOWN":
      tap: $$mdi:mouse-scroll-wheel$$
      hold: $$mdi:arrow-down-bold-circle-outline$$
    "&msc SCRL_UP":
      tap: $$mdi:mouse-scroll-wheel$$
      hold: $$mdi:arrow-up-bold-circle-outline$$
    "&msc SCRL_RIGHT": 
      tap: $$mdi:mouse-scroll-wheel$$
      hold: $$mdi:arrow-right-bold-circle-outline$$

    "&macos_sleep": $$mdi:power-sleep$$

  # ZMK
  zmk_keycode_map:
    # Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL: "="
    PLUS: +
    MINUS: "-"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH: "/"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH: '\'
    BSLH: '\'
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON: ";"
    SEMI: ";"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT: "'"
    APOSTROPHE: <
    APOS: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    DOT: "."
    COMMA: ","
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET: "["
    LBKT: "["
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET: "]"
    RBKT: "]"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE: "`"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    # Numbers
    N1: "1"
    N2: "2"
    N3: "3"
    N4: "4"
    N5: "5"
    N6: "6"
    N7: "7"
    N8: "8"
    N9: "9"
    N0: "0"

    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LGUI: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RGUI: $$mdi:apple-keyboard-command$$
    LS(LA(LCTRL)): $$mdi:triangle$$
    LS(LA(LC(LGUI))): $$mdi:star-four-points$$
    RS(RA(RCTRL)): $$mdi:triangle$$
    RS(RA(RC(RGUI))): $$mdi:star-four-points$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    PG_UP: $$mdi:transfer-up$$
    PG_DN: $$mdi:transfer-down$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:location-exit$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PREVIOUS: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$
    C_PLAY_PAUSE: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    C_SLEEP: $$mdi:power-sleep$$

    # Utils
    LG(LS(N4)): $$mdi:image$$
    LG(LS(N5)): $$mdi:record-rec$$
    LC(LEFT):
      tap: $$mdi:remote-desktop$$
      hold: $$mdi:arrow-left-bold$$
    LC(RIGHT):
      tap: $$mdi:remote-desktop$$
      hold: $$mdi:arrow-right-bold$$
    LC(UP): $$mdi:view-dashboard$$
    LG(SPACE): $$mdi:console-line$$
    LG(A): $$mdi:check-all$$
    LG(Z): $$mdi:undo-variant$$
    LG(X): $$mdi:content-cut$$
    LG(C): $$mdi:content-copy$$
    LG(V): $$mdi:content-paste$$

  zmk_combos:
    cut: { align: bottom, o: 0.15 }
